#!/bin/sh

# installed by CaptainHook 5.19.2

INTERACTIVE="--no-interaction"

vendor/bin/captainhook $INTERACTIVE --configuration=captainhook.json --bootstrap=vendor/autoload.php hook:pre-push "$@" <&0

if [[ $(git status --porcelain) ]]; then
   echo "Uncommited  files present. Aborting push.";
   exit 1;
fi

